name: PharPluginManager
version: 1.1.1
author: PPM-dev
api: 4.0.0
main: ppm\PharPluginManager
description: プラグインマネージャーです
commands:
    ppm:
        description: ppmのメインコマンドです
        usage: /ppm <install | uninstall | update | upgrade | addrepo | delrepo> [args]
        permission: ppm.ppm
permissions:
    ppm.ppm:
        default: op
